package org.hnau.ktcad

/**
 * Hand-written factories for primitives whose placement can be centred on demand.
 *
 * `box`/`cylinder` are generated by KSP like the other `Body` variants, but the generated factory
 * has no `center*` sugar; these replace it (the generator skips `Box`/`Cylinder`). The IR node is
 * unchanged — centring is a `translate`, i.e. pure DSL sugar.
 */

/**
 * A box with its corner at the origin, extending into the `+` octant. A `center*` flag shifts the
 * box by half its size along that axis so the box is centred there instead.
 */
fun box(
    width: Double,
    length: Double,
    height: Double,
    centerX: Boolean = false,
    centerY: Boolean = false,
    centerZ: Boolean = false,
): Solid {
    val box = Solid.Box(width = width, length = length, height = height)
    val dx = if (centerX) -width / 2 else 0.0
    val dy = if (centerY) -length / 2 else 0.0
    val dz = if (centerZ) -height / 2 else 0.0
    return if (dx == 0.0 && dy == 0.0 && dz == 0.0) box else box.translate(dx, dy, dz)
}

/**
 * A cylinder with its base at the origin and axis `+Z`. An [angle] makes a cylindrical wedge. Its
 * base is already centred on the `Z` axis, so `centerX`/`centerY` change nothing (kept for a
 * uniform API); `centerZ` shifts it by half its height.
 */
fun cylinder(
    radius: Double,
    height: Double,
    angle: Double? = null,
    centerX: Boolean = false,
    centerY: Boolean = false,
    centerZ: Boolean = false,
): Solid {
    val cylinder = Solid.Cylinder(radius = radius, height = height, angle = angle)
    return if (centerZ) cylinder.translate(0.0, 0.0, -height / 2) else cylinder
}
