package org.hnau.ktcad

/**
 * Hand-written factories for primitives whose placement can be centred on demand.
 *
 * `box`/`cylinder` are generated by KSP like the other `Body` variants, but the generated factory
 * has no `center*` sugar; these replace it (the generator skips `Box`/`Cylinder`). The IR node is
 * unchanged — centring is a `translate`, i.e. pure DSL sugar.
 */

/**
 * A box with its corner at the origin, extending into the `+` octant. A `center*` flag shifts the
 * box by half its size along that axis so the box is centred there instead.
 */
fun box(
    width: Double,
    length: Double,
    height: Double,
    centerX: Boolean = false,
    centerY: Boolean = false,
    centerZ: Boolean = false,
): Solid = Solid.Box(width = width, length = length, height = height).translate(
    if (centerX) -width / 2 else 0.0,
    if (centerY) -length / 2 else 0.0,
    if (centerZ) -height / 2 else 0.0,
)

/**
 * A cylinder with its base at the origin and axis `+Z`. Its base is already centred on the `Z`
 * axis, so `centerX`/`centerY` change nothing (kept for a uniform API); `centerZ` shifts it by
 * half its height.
 */
fun cylinder(
    radius: Double,
    height: Double,
    centerX: Boolean = false,
    centerY: Boolean = false,
    centerZ: Boolean = false,
): Solid = Solid.Cylinder(radius = radius, height = height).translate(
    0.0,
    0.0,
    if (centerZ) -height / 2 else 0.0,
)
